const fetch = require('node-fetch');
const fs = require('fs');
const { exportProjectAsJson } = require('./export_to_json');

// --- Configuration ---
const REDIRECTS_OUTPUT_FILE = '_redirects'; // Netlify redirects file name

// --- Airtable Configuration (Use Environment Variables in production/Netlify) ---
const AIRTABLE_PAT = process.env.AIRTABLE_PAT;
const BASE_ID = process.env.BASE_ID;
const ITEMS_TABLE_ID = 'tblUA4uuS8IYlhKpD';
const STORES_TABLE_ID = 'Stores';
const SHORTCUT_FIELD_NAME = 'Unique Page Shortcut Name'; // The exact field name
const STORES_FIELD_NAME = 'Stores'; // The exact field name for linked stores

function buildStoreSlug(storeName) {
    if (!storeName || typeof storeName !== 'string') return '';
    return storeName
        .toLowerCase()
        .replace(/[^a-z0-9]+/g, '-')
        .replace(/^-+|-+$/g, '');
}

// --- Fetch Shortcuts Function ---
async function fetchShortcutsFromAirtable() {
    console.log(`\n🌀 Fetching shortcuts from Airtable...`);

    if (!AIRTABLE_PAT || !BASE_ID) {
        console.warn('⚠️ AIRTABLE_PAT or BASE_ID not set. Skipping shortcut fetch.');
        return [];
    }

    let allRecords = [];
    let offset = null;

    const fieldsParams = [
        `fields[]=${encodeURIComponent(SHORTCUT_FIELD_NAME)}`,
        `fields[]=${encodeURIComponent(STORES_FIELD_NAME)}`
    ];
    const fieldsQueryString = fieldsParams.join('&');

    // Filter by records where the shortcut field is not empty
    const filter = encodeURIComponent(`NOT({${SHORTCUT_FIELD_NAME}} = BLANK())`);
    const baseUrl = `https://api.airtable.com/v0/${BASE_ID}/${ITEMS_TABLE_ID}?${fieldsQueryString}&filterByFormula=${filter}`;

    try {
        do {
            let url = baseUrl;
            if (offset) {
                url += `&offset=${offset}`;
            }
            const response = await fetch(url, {
                headers: { 'Authorization': `Bearer ${AIRTABLE_PAT}` }
            });
            if (!response.ok) {
                const errorData = await response.json();
                console.error('Airtable Error fetching shortcuts:', errorData);
                throw new Error(`Failed to fetch shortcuts. Status: ${response.status}`);
            }
            const data = await response.json();
            allRecords = allRecords.concat(data.records);
            offset = data.offset;
        } while (offset);

        console.log(`✅ Found ${allRecords.length} items with shortcuts.`);
        return allRecords;
    } catch (error) {
        console.error('❌ Error fetching shortcut data:', error);
        return []; // Return empty array on error to avoid breaking the build
    }
}


async function fetchStoreNames() {
    if (!AIRTABLE_PAT || !BASE_ID) return {};
    const url = `https://api.airtable.com/v0/${BASE_ID}/${STORES_TABLE_ID}?fields[]=Name`;
    try {
        const response = await fetch(url, {
            headers: { 'Authorization': `Bearer ${AIRTABLE_PAT}` }
        });
        if (!response.ok) return {};
        const data = await response.json();
        const map = {};
        for (const record of data.records) {
            if (record.fields.Name) map[record.id] = record.fields.Name;
        }
        console.log(`✅ Fetched ${Object.keys(map).length} store names for slug generation.`);
        return map;
    } catch (e) {
        console.warn('⚠️ Could not fetch store names:', e.message);
        return {};
    }
}

// --- Generate Redirects Function ---
function generateAndWriteRedirects(shortcutItems, storeNames) {
    console.log(`\n⚙️ Generating ${REDIRECTS_OUTPUT_FILE}...`);
    if (!shortcutItems || shortcutItems.length === 0) {
        console.log('⚠️ No shortcut items found, skipping redirects file generation.');
         try {
             fs.writeFileSync(REDIRECTS_OUTPUT_FILE, '# No redirects generated by build script\n');
         } catch (writeError) {
             console.error(`❌ Error writing empty redirects file: ${writeError.message}`);
         }
        return;
    }

    const redirectLines = [];
    let skippedCount = 0;
    shortcutItems.forEach(item => {
        const shortcut = item.fields[SHORTCUT_FIELD_NAME];
        const storeIds = item.fields[STORES_FIELD_NAME];

        if (!shortcut || typeof shortcut !== 'string' || !shortcut.trim()) {
            console.warn(`\t⚠️ Skipping item ID ${item.id}: Invalid or empty shortcut name.`);
            skippedCount++;
            return;
        }
        if (!storeIds || !Array.isArray(storeIds) || storeIds.length === 0) {
            console.warn(`\t⚠️ Skipping shortcut '/${shortcut.trim()}' (Item ID ${item.id}): Item is not linked to any Stores.`);
            skippedCount++;
            return;
        }

        const firstStoreId = storeIds[0];
        const itemId = item.id;
        const sourcePath = `/${shortcut.trim()}`;
        const storeName = storeNames[firstStoreId];
        const shopParam = storeName ? `shop=${encodeURIComponent(buildStoreSlug(storeName))}` : `shopId=${firstStoreId}`;
        const destinationPath = `/?${shopParam}&openItem=${itemId}`;
        const statusCode = 302;

        redirectLines.push(`${sourcePath} ${destinationPath} ${statusCode}`);
    });

    if (redirectLines.length > 0) {
        const fileContent = `# Netlify redirects generated by build.js\n# ${new Date().toISOString()}\n\n${redirectLines.join('\n')}\n`;
        try {
            fs.writeFileSync(REDIRECTS_OUTPUT_FILE, fileContent);
            console.log(`✅ Successfully wrote ${redirectLines.length} redirect rules to ${REDIRECTS_OUTPUT_FILE}.`);
            if (skippedCount > 0) {
                 console.log(`\tℹ️ Skipped ${skippedCount} items due to missing data.`);
            }
        } catch (error) {
            console.error(`❌ Error writing ${REDIRECTS_OUTPUT_FILE}: ${error.message}`);
        }
    } else {
         console.log(`⚠️ No valid redirect rules generated after filtering.`);
         try {
             fs.writeFileSync(REDIRECTS_OUTPUT_FILE, '# No valid redirects generated by build script\n');
         } catch (writeError) {
             console.error(`❌ Error writing empty redirects file: ${writeError.message}`);
         }
    }
}

// --- Main Build Function ---
async function buildSourceFile() {
    console.log('============================================================');
    console.log('🚀 Starting build process: Generating redirects...');
    console.log('============================================================');

    const shortcutItems = await fetchShortcutsFromAirtable();
    const storeNames = await fetchStoreNames();
    generateAndWriteRedirects(shortcutItems, storeNames);

    // Generate project_source.json snapshot
    console.log('\n📦 Generating project_source.json...');
    try {
        exportProjectAsJson();
    } catch (error) {
        console.warn('⚠️ Could not generate project_source.json:', error.message);
    }

    console.log('\n✨ Build completed successfully! ✨');
}

// Run the build process
buildSourceFile();
