// At the top of build.js, add the require statement:
const fetch = require('node-fetch');
const fs = require('fs');
const path = require('path');

// --- Configuration ---
// ... (keep existing configurations) ...
const REDIRECTS_OUTPUT_FILE = '_redirects'; // Netlify redirects file name

// --- NEW: Airtable Configuration (Use Environment Variables in production/Netlify) ---
const AIRTABLE_PAT = process.env.AIRTABLE_PAT || 'patI1bum8NZvXmYV5.9961c676b00f5e5a9f006c6c26d1ba93ecde2b489f419a68d2a1cb43ff781c57'; // Fallback for local testing if needed
const BASE_ID = process.env.BASE_ID || 'app5yTznb3R5YNUFw'; // Fallback for local testing if needed
const ITEMS_TABLE_ID = 'tblUA4uuS8IYlhKpD';
const SHORTCUT_FIELD_NAME = 'Unique Page Shortcut Name'; // The exact field name
const STORES_FIELD_NAME = 'Stores'; // The exact field name for linked stores

// ... (keep existing getAllFiles, runTextExport, runJsonExport functions) ...

// --- NEW FUNCTION: Fetch Shortcuts from Airtable ---
async function fetchShortcutsFromAirtable() {
    console.log(`\n🌀 Fetching shortcuts from Airtable...`);
    let allRecords = [];
    let offset = null;
    const fields = encodeURIComponent(`fields[]=${SHORTCUT_FIELD_NAME}&fields[]=${STORES_FIELD_NAME}`);
    // Filter by records where the shortcut field is not empty
    const filter = encodeURIComponent(`NOT({${SHORTCUT_FIELD_NAME}} = BLANK())`);
    const baseUrl = `https://api.airtable.com/v0/${BASE_ID}/${ITEMS_TABLE_ID}?${fields}&filterByFormula=${filter}`;

    try {
        do {
            let url = baseUrl;
            if (offset) {
                url += `&offset=${offset}`;
            }
            const response = await fetch(url, {
                headers: { 'Authorization': `Bearer ${AIRTABLE_PAT}` }
            });
            if (!response.ok) {
                const errorData = await response.json();
                console.error('Airtable Error fetching shortcuts:', errorData);
                throw new Error(`Failed to fetch shortcuts. Status: ${response.status}`);
            }
            const data = await response.json();
            allRecords = allRecords.concat(data.records);
            offset = data.offset;
        } while (offset);

        console.log(`✅ Found ${allRecords.length} items with shortcuts.`);
        return allRecords;
    } catch (error) {
        console.error('❌ Error fetching shortcut data:', error);
        return []; // Return empty array on error to avoid breaking the build
    }
}

// --- NEW FUNCTION: Generate and Write Redirects ---
function generateAndWriteRedirects(shortcutItems) {
    console.log(`\n⚙️ Generating ${REDIRECTS_OUTPUT_FILE}...`);
    if (!shortcutItems || shortcutItems.length === 0) {
        console.log('⚠️ No shortcut items found, skipping redirects file generation.');
        // Optionally write an empty file or a file with just placeholder comments
         try {
             fs.writeFileSync(REDIRECTS_OUTPUT_FILE, '# No redirects generated by build script\n');
         } catch (writeError) {
             console.error(`❌ Error writing empty redirects file: ${writeError.message}`);
         }
        return;
    }

    const redirectLines = [];
    let skippedCount = 0;
    shortcutItems.forEach(item => {
        const shortcut = item.fields[SHORTCUT_FIELD_NAME];
        const storeIds = item.fields[STORES_FIELD_NAME];

        // Basic validation
        if (!shortcut || typeof shortcut !== 'string' || !shortcut.trim()) {
            console.warn(`\t⚠️ Skipping item ID ${item.id}: Invalid or empty shortcut name.`);
            skippedCount++;
            return;
        }
        if (!storeIds || !Array.isArray(storeIds) || storeIds.length === 0) {
            console.warn(`\t⚠️ Skipping shortcut '/${shortcut.trim()}' (Item ID ${item.id}): Item is not linked to any Stores.`);
            skippedCount++;
            return;
        }

        const firstStoreId = storeIds[0]; // Use the first linked store
        const itemId = item.id;
        const sourcePath = `/${shortcut.trim()}`; // Use root path
        const destinationPath = `/?shopId=${firstStoreId}&openItem=${itemId}`;
        const statusCode = 302; // Temporary redirect

        redirectLines.push(`${sourcePath} ${destinationPath} ${statusCode}`);
    });

    if (redirectLines.length > 0) {
        const fileContent = `# Netlify redirects generated by build.js\n# ${new Date().toISOString()}\n\n${redirectLines.join('\n')}\n`;
        try {
            fs.writeFileSync(REDIRECTS_OUTPUT_FILE, fileContent);
            console.log(`✅ Successfully wrote ${redirectLines.length} redirect rules to ${REDIRECTS_OUTPUT_FILE}.`);
            if (skippedCount > 0) {
                 console.log(`\tℹ️ Skipped ${skippedCount} items due to missing data.`);
            }
        } catch (error) {
            console.error(`❌ Error writing ${REDIRECTS_OUTPUT_FILE}: ${error.message}`);
        }
    } else {
         console.log(`⚠️ No valid redirect rules generated after filtering.`);
         try {
             fs.writeFileSync(REDIRECTS_OUTPUT_FILE, '# No valid redirects generated by build script\n');
         } catch (writeError) {
             console.error(`❌ Error writing empty redirects file: ${writeError.message}`);
         }
    }
}


// --- MODIFIED Main buildSourceFile function ---
async function buildSourceFile() { // Add async here
    console.log('============================================================');
    console.log('🚀 Starting build process: Text, JSON, and Redirects...'); // Updated message
    console.log('============================================================');

    const timestamp = new Date().toISOString();
    const filePaths = getAllFiles(STARTING_DIRECTORY);
    console.log(`\n➡️ Found ${filePaths.length} project files to include in exports.`);

    // 1. Fetch shortcut data from Airtable (async operation)
    const shortcutItems = await fetchShortcutsFromAirtable();

    // 2. Generate and write the _redirects file (sync operation)
    generateAndWriteRedirects(shortcutItems);

    // 3. Run the old Text Export (sync operation)
    runTextExport(filePaths, timestamp);

    // 4. Run the new JSON Export (sync operation)
    runJsonExport(filePaths, timestamp);

    console.log('\n✨ All build steps completed successfully! ✨');
}

// Run the build process
buildSourceFile();
