# Version: 1.2.1
# Last Modified: 2025-09-02
#
# Changelog:
#
# v1.2.1 - 2025-09-02
#   - Added redirect for Airtable API proxy endpoint.
#
# v1.2.0 - 2025-08-27
#   - Added redirect for the new create-payment-intent API endpoint.
#
# v1.1.0 - 2025-08-26
#   - Added redirect for the new calendar API endpoint.

[build]
  functions = "netlify/functions"
  command = "npm run build"

[[redirects]]
  from = "/api/calendar"
  to = "/.netlify/functions/calendar"
  status = 200

[[redirects]]
  from = "/api/create-payment-intent"
  to = "/.netlify/functions/create-payment-intent"
  status = 200

[[redirects]]
  from = "/api/airtable/*"
  to = "/.netlify/functions/airtable"
  status = 200

[[redirects]]
  from = "/api/pusher-auth"
  to = "/.netlify/functions/pusher-auth"
  status = 200
