/**
 * Header Summary
 * Renders the presentation header (shop logo, event label, running total),
 * event details section (date, goals), plan metrics dashboard, and
 * accordion summaries.
 *
 * Extracted from presentation.js — Phase 6 modularization.
 */

import { state, getRecordById } from '../../state.js';
import { CONSTANTS } from '../../config.js';
import { getRecordPrice } from '../../utils.js';
import { getCurrentUser } from '../../chat.js';
import { log } from '../../utils/debug.js';
import { triggerSave } from '../../events.js';

// Dependencies injected via init()
let _deps = null;

/**
 * Initialize the header summary module.
 * @param {Object} deps
 * @param {Function} deps.renderTaskStatusButton
 * @param {Function} deps.escapeHtml
 * @param {Function} deps.getPresState — returns the presState module
 */
export function init(deps) {
    _deps = deps;
}

export function cleanup() {
    // Dependencies are preserved across hide/show cycles
}

/**
 * Render the event header section (goals, date) with task status buttons.
 */
export function renderEventHeader() {
    const ps = _deps.getPresState();
    const eventName = state.eventDetails.combined.get(CONSTANTS.DETAIL_TYPES.EVENT_NAME) || 'Event Itinerary';
    const goals = state.eventDetails.combined.get(CONSTANTS.DETAIL_TYPES.GOALS) || '';
    const dateValue = state.eventDetails.combined.get(CONSTANTS.DETAIL_TYPES.DATE);

    const summaryEventNotesEl = ps.getSummaryEventNotesEl();
    const summaryEventDateEl = ps.getSummaryEventDateEl();

    // Render goals/notes with task status button
    if (summaryEventNotesEl) {
        if (goals) {
            const goalsStatusBtn = _deps.renderTaskStatusButton('detail', 'goals');
            summaryEventNotesEl.innerHTML = `
                <div class="event-detail-with-status">
                    ${goalsStatusBtn}
                    <span class="detail-content">${_deps.escapeHtml(goals)}</span>
                </div>
            `;
        } else {
            summaryEventNotesEl.innerHTML = '';
        }
    }

    // Render date with task status button
    if (summaryEventDateEl) {
        if (dateValue) {
            const date = Array.isArray(dateValue) ? new Date(dateValue[0]) : new Date(dateValue);
            const dateStr = date.toLocaleDateString('en-US', {
                weekday: 'long',
                month: 'long',
                day: 'numeric',
                year: 'numeric'
            });
            const dateStatusBtn = _deps.renderTaskStatusButton('detail', 'date');
            summaryEventDateEl.innerHTML = `
                <div class="event-detail-with-status">
                    ${dateStatusBtn}
                    <span class="detail-content">${dateStr}</span>
                </div>
            `;
        } else {
            summaryEventDateEl.innerHTML = '';
        }
    }
}

/**
 * Render the presentation header bar (shop logo, title, event label).
 */
export function renderPresentationHeader() {
    const ps = _deps.getPresState();
    const presentationLogoContainer = ps.getPresentationLogoContainer();
    const presentationShopTitle = ps.getPresentationShopTitle();
    const presentationEventLabel = ps.getPresentationEventLabel();

    // Copy the shop logo from the main header
    const mainLogoContainer = document.getElementById('shop-logo-container');
    if (mainLogoContainer && presentationLogoContainer) {
        const mainLogo = mainLogoContainer.querySelector('img');
        if (mainLogo) {
            presentationLogoContainer.innerHTML = `<img src="${mainLogo.src}" alt="${mainLogo.alt || 'Logo'}">`;
        }
    }

    // Copy the shop title from the main header
    const mainShopTitle = document.getElementById('main-shop-title');
    if (mainShopTitle && presentationShopTitle) {
        presentationShopTitle.textContent = mainShopTitle.textContent;
    }

    // Set the event label in the center of the header
    const eventName = state.eventDetails.combined.get(CONSTANTS.DETAIL_TYPES.EVENT_NAME) || 'Event Plan';
    if (presentationEventLabel) {
        presentationEventLabel.textContent = eventName;
        const isAutoGenerated = state.eventDetails.combined.get(CONSTANTS.DETAIL_TYPES.TITLE_AUTO_GENERATED);
        if (isAutoGenerated) {
            presentationEventLabel.classList.add('auto-generated');
        } else {
            presentationEventLabel.classList.remove('auto-generated');
        }
    }
}

/**
 * Update the running total cost displayed in the presentation header.
 */
export function updatePresentationHeaderTotal() {
    const totalEl = document.getElementById('presentation-header-total');
    if (!totalEl) return;

    let subtotal = 0;
    state.cart.lockedItems.forEach((itemInfo, recordId) => {
        const record = getRecordById(recordId);
        if (!record) return;

        const priceParam = (itemInfo.selections && Object.keys(itemInfo.selections).length > 0)
            ? itemInfo.selections
            : itemInfo.selectedOptionIndex;

        let unitPrice = itemInfo.overridePrice ?? getRecordPrice(record, priceParam);
        if (isNaN(unitPrice)) return;

        // Apply package discount
        if (itemInfo.packageId && state.session.activePackages) {
            const packageInfo = state.session.activePackages.get(itemInfo.packageId);
            if (packageInfo && packageInfo.discount > 0) {
                unitPrice = unitPrice * (1 - packageInfo.discount / 100);
            }
        }

        const effectiveQuantity = Math.max(parseFloat(itemInfo.quantity) || 1, 1);
        subtotal += unitPrice * effectiveQuantity;
    });

    const amountReceived = state.session.user.amountReceived || 0;
    const totalDue = subtotal - amountReceived;

    if (subtotal > 0) {
        if (amountReceived > 0) {
            totalEl.textContent = `$${totalDue.toFixed(2)} due`;
        } else {
            totalEl.textContent = `$${subtotal.toFixed(2)}`;
        }
    } else {
        totalEl.textContent = '';
    }
}

/**
 * Update the presentation account button with current user info.
 */
export function updatePresentationAccountButton() {
    const ps = _deps.getPresState();
    const presentationAccountBtn = ps.getPresentationAccountBtn();
    if (!presentationAccountBtn) return;

    const currentUser = getCurrentUser();

    if (currentUser && currentUser.name) {
        presentationAccountBtn.textContent = currentUser.name;
        presentationAccountBtn.title = state.session.user.isAuthenticated
            ? 'Account settings'
            : 'Sign in to save your plan';
    } else {
        presentationAccountBtn.textContent = '';
    }
}

/**
 * Handle user login in presentation view.
 * Removes the old temporary user identity from the collaborators list and
 * re-initializes the presence channel with the authenticated user.
 */
export async function handlePresentationUserLogin() {
    log('Presentation', 'User logged in - updating collaborators and presence');

    const oldTempUserId = localStorage.getItem('chatUserId');

    if (oldTempUserId && state.session.userProfiles.has(oldTempUserId)) {
        log('Presentation', `Removing old temporary user from collaborators: ${oldTempUserId}`);
        state.session.userProfiles.delete(oldTempUserId);
        triggerSave();
    }

    updatePresentationAccountButton();
    _deps.renderCollaborators();

    if (_deps.getPresentationChatPusher()) {
        await _deps.initializePresentationChat();
    }
}

/**
 * Generate summary for the event header accordion.
 */
export function generateHeaderSummary() {
    const ps = _deps.getPresState();
    const headerSummaryEl = ps.getHeaderSummaryEl();
    const dateValue = state.eventDetails.combined.get(CONSTANTS.DETAIL_TYPES.DATE);
    const collaboratorCount = state.session.userProfiles.size;

    let datePart = '';
    if (dateValue) {
        const date = Array.isArray(dateValue) ? new Date(dateValue[0]) : new Date(dateValue);
        datePart = date.toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' });
    }

    let summaryParts = [];
    if (datePart) {
        summaryParts.push(datePart);
    }
    if (collaboratorCount > 0) {
        const hostWord = collaboratorCount === 1 ? 'host' : 'hosts';
        summaryParts.push(`<span class="summary-count">${collaboratorCount}</span> ${hostWord}`);
    }

    const summary = summaryParts.join(' &bull; ') || 'Event details';

    if (headerSummaryEl) {
        headerSummaryEl.innerHTML = summary;
    }
}

/**
 * Update plan metrics displayed across the UI (team count badge).
 */
export function updatePlanSummaryDashboard() {
    const teamCount = state.session.userProfiles?.size || 0;
    const teamCountNumber = document.getElementById('team-count-number');
    if (teamCountNumber) {
        teamCountNumber.textContent = teamCount || 1;
    }
}

/**
 * Generate summary for the items section accordion.
 */
export function generateItemsSummary() {
    const ps = _deps.getPresState();
    const itemsSummaryEl = ps.getItemsSummaryEl();
    const favoritesCount = state.cart.items.size;
    const lockedCount = state.cart.lockedItems.size;
    const totalCount = favoritesCount + lockedCount;

    if (totalCount === 0) {
        if (itemsSummaryEl) {
            itemsSummaryEl.textContent = 'No items added yet';
        }
        return;
    }

    const allItems = [...state.cart.lockedItems.keys(), ...state.cart.items.keys()];
    const itemNames = allItems.slice(0, 3).map(id => {
        const record = getRecordById(id);
        return record?.fields?.Name || 'Item';
    });

    let summary = `<span class="summary-count">${totalCount}</span> item${totalCount !== 1 ? 's' : ''}`;

    if (lockedCount > 0 && favoritesCount > 0) {
        summary += ` (<span class="summary-count">${lockedCount}</span> confirmed, <span class="summary-count">${favoritesCount}</span> idea${favoritesCount !== 1 ? 's' : ''})`;
    } else if (lockedCount > 0) {
        summary += ` (all confirmed)`;
    } else {
        summary += ` (all ideas)`;
    }

    if (itemNames.length > 0) {
        const namePreview = itemNames.join(', ');
        const moreCount = totalCount - itemNames.length;
        summary += ` &bull; <span class="item-preview">${namePreview}${moreCount > 0 ? ` +${moreCount} more` : ''}</span>`;
    }

    if (itemsSummaryEl) {
        itemsSummaryEl.innerHTML = summary;
    }
}
