/**
 * Plan Focus / AI Generation
 * AI-powered plan title/description generation from goal items.
 * Extracted from presentation.js — Phase 1 modularization.
 */

import { state, getRecordById } from '../../state.js';
import { CONSTANTS } from '../../config.js';
import { log } from '../../utils/debug.js';
import { showToast } from '../../ui.js';
import { triggerSave } from '../../events.js';

// Module-level state
let planFocusSuggestionEl = null;
let goalChipsContainerEl = null;
let planFocusGenerateTimer = null;
let pendingPlanFocusSuggestion = null;
let isPlanFocusGenerating = false;
const PLAN_FOCUS_DEBOUNCE_MS = 2000;

// Dependencies
let _renderPresentationHeader = null;
let _renderEventHeader = null;
let _escapeHtml = null;

/**
 * Initialize the plan focus module.
 * @param {Object} deps
 * @param {Function} deps.renderPresentationHeader - Re-renders the presentation header
 * @param {Function} deps.renderEventHeader - Re-renders the event header
 * @param {Function} deps.escapeHtml - HTML escape utility
 * @param {Object} deps.elements - Pre-cached DOM elements
 * @param {HTMLElement} deps.elements.planFocusSuggestionEl
 * @param {HTMLElement} deps.elements.goalChipsContainerEl
 */
export function init({ renderPresentationHeader, renderEventHeader, escapeHtml, elements }) {
    _renderPresentationHeader = renderPresentationHeader;
    _renderEventHeader = renderEventHeader;
    _escapeHtml = escapeHtml;
    if (elements) {
        planFocusSuggestionEl = elements.planFocusSuggestionEl;
        goalChipsContainerEl = elements.goalChipsContainerEl;
    }
}

/**
 * Render goal chips in the header area.
 */
export function renderGoalChips() {
    if (!goalChipsContainerEl) return;

    const goalIds = state.session.goalItems;
    if (!goalIds || goalIds.size === 0) {
        goalChipsContainerEl.innerHTML = '';
        goalChipsContainerEl.style.display = 'none';
        updateRegenerateButton();
        return;
    }

    goalChipsContainerEl.style.display = 'flex';
    let chipsHtml = '';

    for (const recordId of goalIds) {
        const record = getRecordById(recordId);
        if (!record) continue;
        const itemName = record.fields?.Name || 'Item';
        const shortName = itemName.length > 20 ? itemName.substring(0, 18) + '...' : itemName;
        const escaped = _escapeHtml ? _escapeHtml(itemName) : itemName;
        const escapedShort = _escapeHtml ? _escapeHtml(shortName) : shortName;
        chipsHtml += `<span class="goal-chip" data-record-id="${recordId}" title="${escaped}"><span class="goal-chip-star">&#x2B50;</span>${escapedShort}</span>`;
    }

    goalChipsContainerEl.innerHTML = chipsHtml;
    updateRegenerateButton();
}

/**
 * Show or hide the regenerate button based on whether there are goal items.
 */
function updateRegenerateButton() {
    const btn = document.getElementById('plan-focus-regenerate-btn');
    if (!btn) return;

    const hasGoals = state.session.goalItems && state.session.goalItems.size > 0;
    btn.style.display = hasGoals ? 'inline-flex' : 'none';

    if (isPlanFocusGenerating) {
        btn.classList.add('generating');
    } else {
        btn.classList.remove('generating');
    }
}

/**
 * Debounced trigger for plan focus auto-generation.
 * Called whenever goal items change.
 */
export function triggerPlanFocusGeneration() {
    clearTimeout(planFocusGenerateTimer);

    const goalIds = state.session.goalItems;
    if (!goalIds || goalIds.size === 0) {
        hidePlanFocusSuggestion();
        return;
    }

    planFocusGenerateTimer = setTimeout(() => {
        const titleAutoGenerated = state.eventDetails.combined.get(CONSTANTS.DETAIL_TYPES.TITLE_AUTO_GENERATED);
        const currentTitle = state.eventDetails.combined.get(CONSTANTS.DETAIL_TYPES.EVENT_NAME) || '';
        const currentDescription = state.eventDetails.combined.get(CONSTANTS.DETAIL_TYPES.GOALS) || '';

        const shouldGenerate = !currentTitle || titleAutoGenerated ||
            !currentDescription || state.eventDetails.combined.get(CONSTANTS.DETAIL_TYPES.DESCRIPTION_AUTO_GENERATED);

        if (shouldGenerate) {
            generatePlanFocus();
        }
    }, PLAN_FOCUS_DEBOUNCE_MS);
}

/**
 * Call the AI endpoint to generate a plan title/description from goal items.
 */
export async function generatePlanFocus() {
    if (isPlanFocusGenerating) return;

    const goalIds = state.session.goalItems;
    if (!goalIds || goalIds.size === 0) return;

    const goalItemsData = [];
    for (const recordId of goalIds) {
        const record = getRecordById(recordId);
        if (!record) continue;

        const combinedEntry = state.session.combinedItems?.get(recordId);
        const hybridName = combinedEntry?.hybridData?.hybridName;
        const hybridDesc = combinedEntry?.hybridData?.hybridDescription;

        goalItemsData.push({
            name: hybridName || record.fields?.Name || 'Unknown Item',
            description: hybridDesc || record.fields?.Description || ''
        });
    }

    if (goalItemsData.length === 0) return;

    isPlanFocusGenerating = true;
    updateRegenerateButton();
    log('Presentation', `Generating plan focus from ${goalItemsData.length} goal items...`);

    try {
        const currentTitle = state.eventDetails.combined.get(CONSTANTS.DETAIL_TYPES.EVENT_NAME) || '';
        const currentDescription = state.eventDetails.combined.get(CONSTANTS.DETAIL_TYPES.GOALS) || '';

        const response = await fetch('/.netlify/functions/generate-plan-focus', {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({
                goalItems: goalItemsData,
                currentTitle: currentTitle || null,
                currentDescription: currentDescription || null
            })
        });

        if (!response.ok) {
            throw new Error(`API error: ${response.status}`);
        }

        const result = await response.json();
        if (result.success && result.title && result.description) {
            pendingPlanFocusSuggestion = {
                title: result.title,
                description: result.description
            };
            showPlanFocusSuggestion(result.title, result.description);
            log('Presentation', `Plan focus generated: "${result.title}"`);
        }
    } catch (error) {
        console.error('[Presentation] Failed to generate plan focus:', error);
        showToast('Could not generate plan focus', 'warning');
    } finally {
        isPlanFocusGenerating = false;
        updateRegenerateButton();
    }
}

/**
 * Display the plan focus suggestion banner.
 */
function showPlanFocusSuggestion(title, description) {
    if (!planFocusSuggestionEl) return;

    const titleEl = planFocusSuggestionEl.querySelector('.plan-focus-suggestion-title');
    const descEl = planFocusSuggestionEl.querySelector('.plan-focus-suggestion-description');

    if (titleEl) titleEl.textContent = title;
    if (descEl) descEl.textContent = description;

    planFocusSuggestionEl.style.display = 'block';

    const acceptBtn = planFocusSuggestionEl.querySelector('.plan-focus-accept-btn');
    const editBtn = planFocusSuggestionEl.querySelector('.plan-focus-edit-btn');
    const dismissBtn = planFocusSuggestionEl.querySelector('.plan-focus-suggestion-dismiss');

    if (acceptBtn) {
        acceptBtn.onclick = () => applyPlanFocusSuggestion(false);
    }
    if (editBtn) {
        editBtn.onclick = () => applyPlanFocusSuggestion(true);
    }
    if (dismissBtn) {
        dismissBtn.onclick = () => hidePlanFocusSuggestion();
    }
}

/**
 * Hide the plan focus suggestion banner.
 */
export function hidePlanFocusSuggestion() {
    if (planFocusSuggestionEl) {
        planFocusSuggestionEl.style.display = 'none';
    }
    pendingPlanFocusSuggestion = null;
}

/**
 * Apply the pending plan focus suggestion to event name and goals.
 * @param {boolean} allowEdit - If true, prompt user to edit before applying
 */
function applyPlanFocusSuggestion(allowEdit) {
    if (!pendingPlanFocusSuggestion) return;

    let { title, description } = pendingPlanFocusSuggestion;

    if (allowEdit) {
        const editedTitle = prompt('Edit plan title:', title);
        if (editedTitle === null) return;
        title = editedTitle.trim() || title;

        const editedDescription = prompt('Edit plan description:', description);
        if (editedDescription === null) return;
        description = editedDescription.trim() || description;
    }

    state.eventDetails.combined.set(CONSTANTS.DETAIL_TYPES.EVENT_NAME, title);
    state.eventDetails.combined.set(CONSTANTS.DETAIL_TYPES.GOALS, description);
    state.eventDetails.combined.set(CONSTANTS.DETAIL_TYPES.TITLE_AUTO_GENERATED, true);
    state.eventDetails.combined.set(CONSTANTS.DETAIL_TYPES.DESCRIPTION_AUTO_GENERATED, true);

    if (_renderPresentationHeader) _renderPresentationHeader();
    if (_renderEventHeader) _renderEventHeader();

    const eventNameInput = document.getElementById('header-event-name');
    if (eventNameInput) eventNameInput.value = title;
    const goalsInput = document.getElementById('header-goals');
    if (goalsInput) goalsInput.value = description;

    hidePlanFocusSuggestion();

    triggerSave();

    showToast('Plan focus applied', 'success');
    log('Presentation', `Plan focus applied: "${title}"`);
}

/**
 * Initialize event handlers for the plan focus feature.
 */
export function initializeHandlers() {
    const regenerateBtn = document.getElementById('plan-focus-regenerate-btn');
    if (regenerateBtn) {
        regenerateBtn.onclick = () => {
            generatePlanFocus();
        };
    }

    if (goalChipsContainerEl) {
        goalChipsContainerEl.onclick = (e) => {
            const chip = e.target.closest('.goal-chip');
            if (!chip) return;
            const recordId = chip.dataset.recordId;
            if (recordId) {
                const targetItem = document.querySelector(`.itinerary-item[data-record-id="${recordId}"]`);
                if (targetItem) {
                    targetItem.scrollIntoView({ behavior: 'smooth', block: 'center' });
                    targetItem.classList.add('item-highlight');
                    setTimeout(() => targetItem.classList.remove('item-highlight'), 1500);
                }
            }
        };
    }
}

export function cleanup() {
    clearTimeout(planFocusGenerateTimer);
    planFocusSuggestionEl = null;
    goalChipsContainerEl = null;
    planFocusGenerateTimer = null;
    pendingPlanFocusSuggestion = null;
    isPlanFocusGenerating = false;
    _renderPresentationHeader = null;
    _renderEventHeader = null;
    _escapeHtml = null;
}
